name: Bob the Builder

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang
    name: Build ${{ matrix.sysklogd }} using ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        sysklogd: [--with-syslogp, --without-syslogp]
      fail-fast: false
    env:
      MAKEFLAGS: -j3
      CC: ${{ matrix.compiler }}
    steps:
      - name: Install dependencies ...
        run: |
          sudo apt-get -y update
          sudo apt-get -y install tree libite-dev
          wget https://github.com/troglobit/sysklogd/releases/download/v2.5.2/sysklogd-2.5.2.tar.gz
          tar xf sysklogd-2.5.2.tar.gz
          (cd sysklogd-2.5.2/ && ./configure && make && sudo make install-strip)
          sudo ldconfig
      - uses: actions/checkout@v4
      - name: Configure ${{ matrix.sysklogd }} ...
        run: |
          ./autogen.sh
          ./configure --prefix= ${{ matrix.sysklogd }}
      - name: Build ...
        run: |
          make V=1
      - name: Install ...
        run: |
          DESTDIR=~/tmp make install-strip
          tree ~/tmp
          ldd ~/tmp/bin/k8s-logger
          size ~/tmp/bin/k8s-logger
          ~/tmp/bin/k8s-logger -h
          ~/tmp/bin/k8s-logger -v
