name: Release General

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and upload release tarball
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies ...
        run: |
          sudo apt-get -y update
          sudo apt-get -y install tree libite-dev
          wget https://github.com/troglobit/sysklogd/releases/download/v2.5.2/sysklogd-2.5.2.tar.gz
          tar xf sysklogd-2.5.2.tar.gz
          (cd sysklogd-2.5.2/ && ./configure && make && sudo make install-strip)
          sudo ldconfig
      - name: Configure ...
        run: |
          ./autogen.sh
          ./configure --with-syslogp
      - name: Build release ...
        run: |
          make release
          ls -lF ../
          mkdir -p artifacts/
          mv ../*.tar.* artifacts/
      - name: Extract ChangeLog entry ...
        run: |
          awk '/-----*/{if (x == 1) exit; x=1;next}x' ChangeLog.md |head -n -1 > release.md
          cat release.md
      - uses: ncipollo/release-action@v1
        with:
          name: k8s-logger ${{ github.ref_name }}
          bodyFile: "release.md"
          artifacts: "artifacts/*"
